### ISSUE TITLE
弱弱地问一个问题 🙋 

### ISSUE THREAD

**Issue by BensonLaur** [MingYueRuYa/worktools#1]
:snail: 弱弱地问一个问题 🙋

为什么不同的文件夹用  monkey :monkey:   dolphin 🐬 :    cattle  :cow:   来命名呢？:joy:

**Comment by MingYueRuYa** [comment]
好问题。分类的确不好，待我有时间整理下。

**Comment by BensonLaur** [comment]
> 好问题。分类的确不好，待我有时间整理下。

哈哈行，不整理也行，确实也只是好奇觉得有趣

我也是用了其中一个 ```dolphin/dolproductinfo.h``` 的类一段时间，突然不理解这个 dol 前缀才反应过来回来看看有没有说明 😄

**Comment by MingYueRuYa** [comment]
dol前缀，就是dolphin取自前三个缩写。
